version: 2.1

jobs:
  react-native-android-setup:
    docker:
      - image: reactnativecommunity/react-native-android:latest # Preconfigured image

    steps:
      - checkout
      - run:
          name: Latest commit from Main branch
          command: git pull && git fetch
      - run:
          name: Verify Environment Setup
          command: |
            java -version
            echo "JAVA_HOME is $JAVA_HOME"
            echo "ANDROID_HOME is $ANDROID_HOME"
            sdkmanager --list || echo "SDK tools are ready for use."

workflows:
  android:
    jobs:
      - react-native-android-setup
