version: 2.1

jobs:
  react-native-android-setup:
    docker:
      - image: reactnativecommunity/react-native-android:latest # Docker image for the job

    steps:
      - setup_remote_docker: # Enables remote Docker for layer caching
          version: 20.10.16
      - run:
          name: Pre-pull Docker Image
          command: docker pull reactnativecommunity/react-native-android:latest
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages-
      - run:
          name: Install Yarn Dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

workflows:
  android:
    jobs:
      - react-native-android-setup
