version: 2.1

jobs:
  react-native-android-setup:
    docker:
      - image: reactnativecommunity/react-native-android:latest

    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages-
      - run:
          name: Install Yarn Dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - restore_cache:
          name: Restore Gem Cache
          keys:
            - gem-cache-{{ checksum "Gemfile.lock" }}
            - gem-cache-
      - run:
          name: Install Gems
          command: bundle install --path vendor/bundle
      - save_cache:
          name: Save Gem Cache
          key: gem-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Run Unit Tests
          command: |
            mkdir -p test-reports
            yarn test --outputFile=test-reports/test-results.json --json
      - store_artifacts:
          name: Save Test Report
          path: test-reports/test-results.json

workflows:
  android:
    jobs:
      - react-native-android-setup
