version: 2.1

jobs:
  react-native-android-setup:
    docker:
      - image: reactnativecommunity/react-native-android:latest

    steps:
      - checkout # Ensure code is checked out before caching steps
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages-
      - run:
          name: Install Yarn Dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

workflows:
  android:
    jobs:
      - react-native-android-setup
