version: 2.1

jobs:
  react-native-android-setup:
    docker:
      - image: reactnativecommunity/react-native-android:latest

    steps:
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Yarn Dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      # - run:
      #     name: Verify Environment Setup
      #     command: |
      #       java -version
      #       echo "JAVA_HOME is $JAVA_HOME"
      #       echo "ANDROID_HOME is $ANDROID_HOME"
      #       sdkmanager --list || echo "SDK tools are ready for use."

workflows:
  android:
    jobs:
      - react-native-android-setup
