version: 2.1

jobs:
  react-native-android-setup:
    docker:
      - image: reactnativecommunity/react-native-android:latest

    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
            - yarn-cache-
      - run:
          name: Install Dependencies (Yarn)
          command: |
            if [ ! -d "node_modules" ]; then
              echo "Node modules not found, running yarn install..."
              yarn install
            else
              echo "Node modules found, skipping yarn install."
            fi
      - save_cache:
          paths:
            - node_modules
          key: yarn-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Latest commit from Main branch
          command: git pull && git fetch
      - run:
          name: Verify Environment Setup
          command: |
            java -version
            echo "JAVA_HOME is $JAVA_HOME"
            echo "ANDROID_HOME is $ANDROID_HOME"
            sdkmanager --list || echo "SDK tools are ready for use."

workflows:
  android:
    jobs:
      - react-native-android-setup
