default_platform(:android)

platform :android do
  desc "Increment versionCode and versionName"
  lane :increment do
    increment_version_name(
      app_project_dir: 'android/app',
      bump_type: 'minor'
    )
    increment_version_code(
      app_project_dir: 'android/app'
    )
  end

  desc "Runs all the tests"
  lane :debugAPK do
    gradle(
      task: "test",
      project_dir: "android"
    )
  end

  lane :releaseAPK do
    gradle(
      task: "release",
      project_dir: "android"
    )
  end

    lane :releaseAAB do
    gradle(
      task: "bundle",
      project_dir: "android"
    )
  end

  lane :betaAndroid do
    increment
    debugAPK
  end

  lane :releaseAndroid do
    increment
    releaseAPK
  end

   lane :releaseStore do
    increment
    releaseAAB
  end
end
