name: Build Android App

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Restore Environment
        uses: actions/download-artifact@v3
        with:
          name: android-env-cache

      - name: Decode Keystore
        run: echo "${{ secrets.PRODUCTION_KEY_STORE_FILE }}" | base64 --decode > /tmp/my-upload-key.keystore

      - name: Verify Decoded Keystore
        run: |
          keytool -list -v -keystore /tmp/my-upload-key.keystore -storepass "${{ secrets.PRODUCTION_KEY_STORE_PASSWORD }}"
        env:
          JAVA_OPTS: '-Dfile.encoding=UTF-8'

      - name: Build Android APK with Fastlane
        env:
          PRODUCTION_KEY_STORE_FILE: /tmp/my-upload-key.keystore
          PRODUCTION_KEY_STORE_PASSWORD: ${{ secrets.PRODUCTION_KEY_STORE_PASSWORD }}
          PRODUCTION_KEY_KEY_ALIAS: ${{ secrets.PRODUCTION_KEY_KEY_ALIAS }}
          PRODUCTION_KEY_KEY_PASSWORD: ${{ secrets.PRODUCTION_KEY_KEY_PASSWORD }}
        run: |
          bundle exec fastlane betaAndroid local:false

      - name: Upload APK Release
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }} -  App Release Artifacts - Release APK && AAB
          path: |
            android/app/build/outputs/apk/release/app-release.apk
            android/app/build/outputs/bundle/release/app-release.aab
