name: Build Android App

env:
  main_project_module: ReactNativeCI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Node.Js
        uses: actions/setup-node@v3
        with:
          node-version: 23.x
          cache: 'yarn'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Enable Corepack and Set Yarn Version
        run: |
          corepack enable
          corepack prepare yarn@4.6.0 --activate

      - name: Cache Yarn Dependencies
        uses: actions/cache@v3
        with:
          path: ./yarn/cache
          key: yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-cache-

      - name: Install Yarn Dependencies
        run: yarn install

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      # - name: Setup Fastlane
      #   run: bundle install

      # - name: Build Android APK
      #   run: |
      #     fastlane betaAndroid
