name: Build Android App

env:
  main_project_module: ReactNativeCI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Cache Android SDK
        id: cache-android-sdk
        uses: actions/cache@v3
        with:
          path: ~/.android
          key: android-sdk-${{ runner.os }}-${{ hashFiles('**/build.gradle', '**/build.gradle.kts') }}
          restore-keys: |
            android-sdk-${{ runner.os }}-

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/*.kts') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Node.Js
        uses: actions/setup-node@v3
        with:
          node-version: 23.x
          cache: 'yarn'

      - name: Setup Android SDK
        if: steps.cache-android-sdk.outputs.cache-hit != 'true'
        uses: android-actions/setup-android@v2

      - name: Enable Corepack and Set Yarn Version
        run: |
          corepack enable
          corepack prepare yarn@4.6.0 --activate

      - name: Cache Yarn Dependencies
        uses: actions/cache@v3
        with:
          path: ./yarn/cache
          key: yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-cache-

      - name: Install Yarn Dependencies
        run: yarn install

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Cache Ruby Gems
        id: gems-cache
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: gems-cache-${{ runner.os }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            gems-cache-${{ runner.os }}-

      - name: Install Bundle Dependencies
        if: steps.gems-cache.outputs.cache-hit != 'true'
        run: |
          bundle config set path 'vendor/bundle'
          bundle install --jobs 4 --retry 3

      - name: Setup Fastlane
        run: |
          bundle config set path 'vendor/bundle'
          bundle install --jobs 4 --retry 3

      - name: Build Android APK
        run: |
          bundle exec fastlane betaAndroid

      - name: Upload APK Release
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }} -  App Release APK generated
          path: android/app/build/outputs/bundle/release/*.apk
